spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    active: secret
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: postgres
